import type { Filter, FiltersList } from '~/types/types';

// фейковые данные для фильтров
const filters: FiltersList = {
  courses_simple: [
    {
      title: 'Мое избранное',
      name: 'favoriteFilters',
      queryParam: 'favorites',
      filters: [{ id: 'f@only', type: 'checkbox', name: 'Показать', value: false, queryParam: 'favorites' }],
    },
    /* старая версия с точной формой обучения (см. ниже новую версию с обобщенной)
    {
      title: 'Форма обучения',
      name: 'formatFilters',
      queryParam: 'format',
      showAll: true,
      filters: [
        { id: 'full_time', type: 'checkbox', name: 'Очная', value: false, queryParam: 'format' },
        { id: 'full_time_dot', type: 'checkbox', name: 'Очная с применением ДОТ', value: false, queryParam: 'format' },
        { id: 'full_time_distance', type: 'checkbox', name: 'Очно-заочная', value: false, queryParam: 'format' },
        { id: 'distance_dot', type: 'checkbox', name: 'Заочная с применением ДОТ', value: false, queryParam: 'format' },
        { id: 'full_time_distance_dot', type: 'checkbox', name: 'Очно-заочная с применением ДОТ', value: false, queryParam: 'format' },
        { id: 'distance_auto', type: 'checkbox', name: 'Дистанционная с автоматической проверкой', value: false, queryParam: 'format' },
        { id: 'distance_manual', type: 'checkbox', name: 'Дистанционная с проверкой преподавателем', value: false, queryParam: 'format' },
      ],
    },
    */
    {
      title: 'Форма обучения',
      name: 'formatTypeFilters',
      queryParam: 'formatType',
      filters: [
        { id: 'full_time', type: 'checkbox', name: 'Очные', value: false, queryParam: 'formatType' },
        { id: 'part_time', type: 'checkbox', name: 'Заочные', value: false, queryParam: 'formatType' },
        { id: 'online', type: 'checkbox', name: 'Онлайн', value: false, queryParam: 'formatType' },
      ],
    },
    {
      title: 'Оплата',
      name: 'fundingFilters',
      queryParam: 'funding',
      filters: [
        { id: 'off_budget', type: 'checkbox', name: 'Внебюджетный', value: false, queryParam: 'funding' },
        { id: 'budget', type: 'checkbox', name: 'Бюджетный', value: false, queryParam: 'funding' },
        { id: 'subsidized', type: 'checkbox', name: 'Городская субсидия', value: false, queryParam: 'funding' },
      ],
    },
    /* период обучения с годами пока отключен
    {
      title: 'Период обучения',
      name: 'academicYearFilters',
      queryParam: 'academicYear',
      filters: [
        { id: '2024/2025', type: 'checkbox', name: '2024/2025', value: false, queryParam: 'academicYear' },
        { id: '2025/2026', type: 'checkbox', name: '2025/2026', value: false, queryParam: 'academicYear' },
      ],
    },
    */
    {
      // TODO: грузить из базы, показывать свернуто только самые популярные /api/v1/courses/filter-fields
      // TODO: переработать логику фильтров, сейчас id должны быть уникальны, а надо добавлять префиксы автоматически, а не вручную
      title: 'Организации',
      name: 'organizationFilters',
      queryParam: 'organization',
      searchable: true,
      showToggle: true,
      filters: [
        {
          id: 'o@118',
          type: 'checkbox',
          name: 'ГАОУ ДПО «Корпоративный университет»',
          value: false,
          queryParam: 'organization',
        },
        //{ id: 'o@1', type: 'checkbox', name: 'Корпоративный Университет', value: false, queryParam: 'organization' },
        {
          id: 'o@105',
          type: 'checkbox',
          name: 'АНО «Институт прикладного анализа поведения и психолого-социальных технологий»',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@6',
          type: 'checkbox',
          name: 'АО «Издательство «Просвещение»',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@3',
          type: 'checkbox',
          name: 'ГАОУ ВО «Московский городской педагогический университет»',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@13',
          type: 'checkbox',
          name: 'ГАОУ ДПО «Московский центр качества образования» (МЦКО)',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@204',
          type: 'checkbox',
          name: 'ГБОУ ДПО «Московский центр воспитательных практик»',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@16',
          type: 'checkbox',
          name: 'ГБУ «Городской психолого-педагогический центр» (ГППЦ)',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@25',
          type: 'checkbox',
          name: 'НОУ ДПО «Институт новых технологий»',
          value: false,
          queryParam: 'organization',
        },
        { id: 'o@168', type: 'checkbox', name: 'ООО «ДОП ЛИГА»', value: false, queryParam: 'organization' },
        {
          id: 'o@31',
          type: 'checkbox',
          name: 'ФГАОУ ВО «Национальный исследовательский технологический университет «МИСиС»',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@23',
          type: 'checkbox',
          name: 'ФГАОУ ВО Первый МГМУ им. И.М. Сеченова Минздрава России (Сеченовский Университет)',
          value: false,
          queryParam: 'organization',
        },
        {
          id: 'o@48',
          type: 'checkbox',
          name: 'ФГБОУ ВО «Московский педагогический государственный университет» (МПГУ)',
          value: false,
          queryParam: 'organization',
        },
      ],
    },
    {
      // TODO: грузить из базы, показывать свернуто только самые популярные /api/v1/courses/filter-fields
      title: 'Направления',
      name: 'studyDirectionFilters',
      queryParam: 'studyDirection',
      searchable: true,
      showToggle: true,
      filters: [
        {
          id: 'sd@7',
          type: 'checkbox',
          name: 'Государственная итоговая аттестация (9 и 11 кл.)',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@17',
          type: 'checkbox',
          name: 'Профессиональная переподготовка',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@29',
          type: 'checkbox',
          name: 'Проектно-исследовательская деятельность',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@37',
          type: 'checkbox',
          name: 'Образовательные технологии',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@38',
          type: 'checkbox',
          name: 'Дополнительное образование и внеурочная деятельность детей',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@8',
          type: 'checkbox',
          name: 'Духовно-нравственное воспитание, ОРКСЭ',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@28', type: 'checkbox', name: 'Предметное обучение', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@35',
          type: 'checkbox',
          name: 'Предпрофессиональная подготовка и профильное обучение',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@9',
          type: 'checkbox',
          name: 'Информационно-коммуникационные технологии',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@12', type: 'checkbox', name: 'Методическая работа', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@20',
          type: 'checkbox',
          name: 'Психолого-педагогическая поддержка образовательного процесса',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@36', type: 'checkbox', name: 'Дошкольное образование', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@11',
          type: 'checkbox',
          name: 'Коррекционно-развивающее обучение, дефектология, логопедия',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@22',
          type: 'checkbox',
          name: 'Работа с обучающимися с ОВЗ',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@6', type: 'checkbox', name: 'Воспитательная работа', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@25',
          type: 'checkbox',
          name: 'Социальная работа в школе',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@19', type: 'checkbox', name: 'Профилактическая работа', value: false, queryParam: 'studyDirection' },
        { id: 'sd@24', type: 'checkbox', name: 'Здоровьесбережение', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@15',
          type: 'checkbox',
          name: 'Совершенствование педагогического мастерства',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@33', type: 'checkbox', name: 'Коммуникация', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@26',
          type: 'checkbox',
          name: 'Федеральные государственные образовательные стандарты (ФГОС)',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@10',
          type: 'checkbox',
          name: 'Искусство (музыка, МХК, ИЗО)',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@39', type: 'checkbox', name: 'Читательская грамотность', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@42',
          type: 'checkbox',
          name: 'Математическая грамотность',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@45', type: 'checkbox', name: 'Метапредметность', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@44',
          type: 'checkbox',
          name: 'Естественнонаучная грамотность',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@14',
          type: 'checkbox',
          name: 'Патриотическое воспитание',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@16', type: 'checkbox', name: 'Подготовка к олимпиадам', value: false, queryParam: 'studyDirection' },
        { id: 'sd@23', type: 'checkbox', name: 'Развитие талантов', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@41',
          type: 'checkbox',
          name: 'Функциональная грамотность',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@30',
          type: 'checkbox',
          name: 'Управление образовательной организацией',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@47', type: 'checkbox', name: 'Финансовая грамотность', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@43',
          type: 'checkbox',
          name: 'Среднее профессиональное образование',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@59', type: 'checkbox', name: 'Креативность', value: false, queryParam: 'studyDirection' },
        { id: 'sd@32', type: 'checkbox', name: 'МЭШ', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@34',
          type: 'checkbox',
          name: 'Сопровождение деятельности ОО',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@49', type: 'checkbox', name: 'Классное руководство', value: false, queryParam: 'studyDirection' },
        { id: 'sd@50', type: 'checkbox', name: 'Искусственный интеллект', value: false, queryParam: 'studyDirection' },
        { id: 'sd@57', type: 'checkbox', name: 'Критическое мышление', value: false, queryParam: 'studyDirection' },
        { id: 'sd@60', type: 'checkbox', name: 'Мотивация', value: false, queryParam: 'studyDirection' },
        { id: 'sd@54', type: 'checkbox', name: 'Эмоциональный интеллект', value: false, queryParam: 'studyDirection' },
        { id: 'sd@46', type: 'checkbox', name: 'Обеспечение безопасности', value: false, queryParam: 'studyDirection' },
        {
          id: 'sd@18',
          type: 'checkbox',
          name: 'Профессиональный стандарт "Педагог"',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@21',
          type: 'checkbox',
          name: 'Работа с детьми мигрантами',
          value: false,
          queryParam: 'studyDirection',
        },
        {
          id: 'sd@40',
          type: 'checkbox',
          name: 'Русский язык как иностранный',
          value: false,
          queryParam: 'studyDirection',
        },
        { id: 'sd@27', type: 'checkbox', name: 'Школьная библиотека', value: false, queryParam: 'studyDirection' },
      ],
    },
  ],

  courses: [
    {
      title: 'Дата',
      name: 'dataFilters',
      filters: [
        { id: 'fzxc1', type: 'checkbox', name: 'Популярные', value: false },
        { id: 'fzxcd2', type: 'checkbox', name: 'Новые', value: false },
      ],
    },
    {
      title: 'Популярные',
      name: 'popularFilters',
      filters: [
        { id: 'f1', type: 'checkbox', name: 'Популярные', value: false },
        { id: 'f2', type: 'checkbox', name: 'Новые', value: false },
      ],
    },
    {
      title: 'Направления',
      name: 'directionFilters',
      filters: [
        { id: 'f223', type: 'checkbox', name: 'Воспитательная работа', value: false },
        { id: 'f224', type: 'checkbox', name: 'Государственная итоговая аттестация (9 и 11 кл.)', value: true },
        { id: 'f225', type: 'checkbox', name: 'Математика', value: false },
        { id: 'f226', type: 'checkbox', name: 'Русский язык', value: false },
        { id: 'f227', type: 'checkbox', name: 'Литература', value: false },
        { id: 'f228', type: 'checkbox', name: 'История', value: false },
        { id: 'f229', type: 'checkbox', name: 'Обществознание', value: false },
        { id: 'f230', type: 'checkbox', name: 'Физика', value: false },
        { id: 'f231', type: 'checkbox', name: 'Химия', value: false },
        { id: 'f232', type: 'checkbox', name: 'Биология', value: false },
        { id: 'f233', type: 'checkbox', name: 'География', value: false },
      ],
    },
    {
      title: 'Стоимость',
      name: 'costFilters',
      sliderData: true,
      filters: [
        { id: 'f116', type: 'checkbox', name: 'Бюджетный', value: false },
        { id: 'f117', type: 'checkbox', name: 'Городская субсидия', value: false },
        { id: 'fafda1', type: 'slider', pos: 'to', name: 'от', value: 20 },
        { id: 'fafda2', type: 'slider', pos: 'from', name: 'от', value: 40 },
      ],
    },
    {
      title: 'Длительность, часов',
      name: 'durationFilters',
      filters: [
        { id: 'd1', type: 'checkbox', name: '1 час', value: false },
        { id: 'd2', type: 'checkbox', name: '2 часа', value: false },
        { id: 'd3', type: 'checkbox', name: '3 часа', value: false },
        { id: 'd4', type: 'checkbox', name: '4 часа', value: false },
        { id: 'd5', type: 'checkbox', name: '5 часов', value: false },
        { id: 'd6', type: 'checkbox', name: '6 часов', value: false },
        { id: 'd7', type: 'checkbox', name: '7 часов', value: false },
        { id: 'd8', type: 'checkbox', name: '8 часов', value: false },
        { id: 'd9', type: 'checkbox', name: '9 часов', value: false },
        { id: 'd10', type: 'checkbox', name: '10 часов', value: false },
      ],
    },
    {
      title: 'Форма обучения',
      name: 'educationFormFilters',
      filters: [
        { id: 'ef1', type: 'checkbox', name: 'Очная', value: false },
        { id: 'ef2', type: 'checkbox', name: 'Заочная', value: false },
        { id: 'ef3', type: 'checkbox', name: 'Дистанционная', value: false },
        { id: 'ef4', type: 'checkbox', name: 'Очно-заочная', value: false },
        { id: 'ef5', type: 'checkbox', name: 'Семейное образование', value: false },
        { id: 'ef6', type: 'checkbox', name: 'Индивидуальное обучение', value: false },
        { id: 'ef7', type: 'checkbox', name: 'Групповое обучение', value: false },
        { id: 'ef8', type: 'checkbox', name: 'Колледж', value: false },
        { id: 'ef9', type: 'checkbox', name: 'Университет', value: false },
        { id: 'ef10', type: 'checkbox', name: 'Другое', value: false },
      ],
    },
    {
      title: 'Организатор',
      name: 'organizerFilters',
      filters: [
        { id: 'o1', type: 'checkbox', name: 'Учебное заведение', value: false },
        { id: 'o2', type: 'checkbox', name: 'Тренинг-центр', value: false },
        { id: 'o3', type: 'checkbox', name: 'Курсы', value: false },
        { id: 'o4', type: 'checkbox', name: 'Консалтинговая компания', value: false },
        { id: 'o5', type: 'checkbox', name: 'Бизнес-школа', value: false },
        { id: 'o6', type: 'checkbox', name: 'Онлайн-платформа', value: false },
        { id: 'o7', type: 'checkbox', name: 'Общественная организация', value: false },
        { id: 'o8', type: 'checkbox', name: 'Частное лицо', value: false },
        { id: 'o9', type: 'checkbox', name: 'Государственная организация', value: false },
        { id: 'o10', type: 'checkbox', name: 'Другое', value: false },
      ],
    },
  ],
  teachers_simple: [
    {
      title: 'Организации',
      name: 'professionFilters',
      queryParam: 'professionFilters',
      searchable: true,
      showToggle: true,
      filters: [],
    },
    {
      title: 'Направления',
      name: 'studyDirectionFilters',
      queryParam: 'studyDirectionFilters',
      searchable: true,
      showToggle: true,
      filters: [],
    },
  ],
  organizationFilters: [
    {
      title: 'Организации',
      name: 'organizationFilters',
      queryParam: 'organizationFilters',
      searchable: true,
      showToggle: true,
      filters: [],
    },
  ],
};

export function getFilters() {
  return filters;
}
